# Generated by Django 4.2.3 on 2023-07-24 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год выпуска')),
            ],
            options={
                'verbose_name': 'Лодка',
                'verbose_name_plural': 'Лодки',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=158, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='BoatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='владел с')),
                ('stop_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='владел до')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.boat', verbose_name='лодка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boats.owner', verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.AddField(
            model_name='boat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.owner', verbose_name='владелец'),
        ),
    ]
